### ISSUE TITLE
As an EM I want MEGA to verify travel time to and from out-of-house work, so that I will be informed if there are errors in my logging.

### ISSUE THREAD

**Issue by sthausmann** [Gepardec/mega#201] opened 2020-10-05 09:06 UTC
If you set the location of a work entry in ZEP to anything but 'Erste Tätigkeitsstätte' without logging travel time to and from, then MEGA should recognize this as an erroneous entry

This can be reproduced at will
ZEP does recognize this and show an alert on the 'Kostenabrechnung' tab.

**Comment by cchet** [comment] 2020-10-05 15:42
@sthausmann 
That is a feature request, not a bug, this hasn't been implemented yet

**Comment by cchet** [comment] 2020-11-06 06:50
Here we have now specified test scenarios https://github.com/Gepardec/mega/wiki/Tests but we need to refactor the checks of the project times, so this is maybe not event meant to be released in Mega 2.0

**Closed** 2021-02-24 09:35 UTC
Labels: enhancement, user story
